api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'tobacco', views.TobaccoViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',
        namespace='rest_framework'))
]

article/urls.py
from django.urls import path
from article import views

urlpatterns = [
    path(r'article/get/<int:article_id>', views.ArticleView.as_view()),
    path(r'article/addlike/<int:article_id>', views.AddLike.as_view()),
    path(r'article/addcoment/<int:article_id>', views.AddComment.as_view()),
    path(r'article/add', views.AddArticle.as_view()),
    path(r'page/<int:page>', views.Articles.as_view()),
    path(r'', views.Articles.as_view()),
]

firstapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^base/', include('article.urls')),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^tobacco/', include('tobacco.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^', include('article.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

article/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Article(models.Model):
    class Meta():
        db_table = "article"
    article_title = models.CharField(max_length=200)
    article_text = models.TextField()
    article_date = models.DateTimeField(default=datetime(1970, 1, 1))
    article_likes = models.IntegerField(default=0)


class Comments(models.Model):
    class Meta():
        db_table = 'Comments'
    comments_user = models.ForeignKey(User, on_delete=models.CASCADE)
    comments_text = models.TextField()
    comments_article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comments_date = models.DateTimeField(default=datetime(1970, 1, 1))

article/forms.py
from django.forms import ModelForm
from article.models import Comments, Article


class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ['comments_text']


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['article_title', 'article_text']

article/views.py
from time import strftime, localtime
from django.views import View
from django.http.response import Http404
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render_to_response, redirect
from article.models import Article, Comments
from django.contrib.auth.models import User
from article.forms import CommentForm, ArticleForm
from django.template.context_processors import csrf
from django.contrib import auth
from django.core.paginator import Paginator

now_time = strftime("%Y-%m-%d %H:%M:%S", localtime())


class Articles(View):
    def get(self, request, *args, **kwargs):
        page_number = kwargs.get('page', 1)
        all_articles = Article.objects.all().order_by('-article_date')
        paginator = Paginator(all_articles, 2)
        page = paginator.page(page_number)
        args = {}
        args['articles'] = page
        args['username'] = auth.get_user(request).username
        args['pages'] = paginator.page_range
        return render_to_response('articles.html', args)


class ArticleView(View):
    def get(self, request, article_id=1):
        coment_form = CommentForm
        args = {}
        args.update(csrf(request))
        args['article'] = Article.objects.get(id=article_id)
        args['comments'] = Comments.objects.filter(comments_article=article_id)
        args['form'] = coment_form
        args['username'] = auth.get_user(request).username
        return render_to_response('article.html', args)


class AddLike(View):
    def get(self, request, article_id, *args, **kwargs):
        try:
            if str(article_id) in request.COOKIES:
                return redirect('/')
            else:
                article = Article.objects.get(id=article_id)
                article.article_likes += 1
                article.save()
                response = redirect('/')
                response.set_cookie(str(article_id), True)
                return response
        except ObjectDoesNotExist:
            raise Http404
        return redirect('/')


class AddComment(View):
    def get(self, request, article_id, *args, **kwargs):
        url = request.META.get('HTTP_REFERER')
        return redirect(url)

    def post(self, request, article_id, *args, **kwargs):
        if 'pause' not in request.session:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.comments_article = Article.objects.get(id=article_id)
                comment.comments_date = now_time
                user_id = auth.get_user(request).id
                comment.comments_user = User.objects.get(id=user_id)
                form.save()
                request.session.set_expiry(60)
                request.session['pause'] = True
        url = request.META.get('HTTP_REFERER')
        return redirect(url)


class AddArticle(View):
    def get(self, request, *args, **kwargs):
        form = ArticleForm
        args = {}
        args.update(csrf(request))
        args['form'] = form
        args['username'] = auth.get_user(request).username
        return render_to_response('add_article.html', args)

    def post(self, request, *args, **kwargs):
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.article_date = now_time
            form.save()
        return redirect('/')

article/templates/add_article.html
{% extends "main.html" %}
{% block article %}
    {% if username %}    
        <div class="row justify-content-md-center">
            <div class="col col-sm-6">
                <form action="/article/add" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="form-group">                                    
                            <label for="{{form.article_title.id_for_label}}">Заголовок статьи:</label>
                            <input class="form-control" id="{{form.article_title.id_for_label}}" name="{{form.article_title.html_name}}"/>
                        </div>
                        <div class="form-group">                                    
                            <label for="{{form.article_text.id_for_label}}">Текст статьи</label>
                            <textarea class="form-control" id="{{form.article_text.id_for_label}}" name="{{form.article_text.html_name}}" rows="10" cols="40"></textarea>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-primary" value="Добавить статью">
                </form> 
            </div>
        </div>
    {% else %}
        <p>Только авторизованные пользователи могут добавлять статьи</p>
        <a href="/auth/login" class="button radius large">Авторизироваться</a>
    {% endif %}
{% endblock article %}

article/templates/article.html
{% extends "main.html" %}
{% block article %}
 
    <div class="col col-md-6 offset-1">
        <h4> 
            <a href="/article/get/{{ article.id }}">{{article.article_title}}</a>
        
        <div class="float-right"> <h6><small>{{article.article_date}}</small> </h6> </div>
    </div>

    <div class="col-11 col-md-6 offset-1 ">
        <div class="bg-white rounded bordered my-1 p-1 p-3">
       {{article.article_text}}
       
    </div>
        <hr>        
        {%if not comments %}

            <p>Еше никто не оставил комментарий к данной статье</p>
        {% endif %}

        {% for comment in comments %}     
        <div class="col bg-white rounded bordered my-1 p-1 shadow-sm">        
            <h6>
                <b><a href="#">{{ comment.comments_user.username}}</a></b> <small class="text-secondary">{{ comment.comments_date}}</small>
            </h6>
            <p class="h6 mx-3"><small>{{comment.comments_text}}</small></p> 
        </div>
        {% endfor %}

        {% if username %}
            <form action="/article/addcoment/{{ article.id }}" method="POST">
                <div class="form-group ">
                {% csrf_token %}
                <label for="id_comments_text">Comments text:</label>
                <textarea class="form-control shadow" name="comments_text" id="id_comments_text" rows="3"></textarea>
                <button type="submit" class="btn btn-primary shadow mt-3">Добавить комментирй</button>
            </div>
            </form>
        {% else %}
            <p>Только авторизированные пользователи могут оставлять комментарии</p>
            <a href="/auth/login" class="btn btn-primary shadow">Авторизироваться</a>
        {% endif %}
    </div>   

{% endblock article %}

article/templates/articles.html
{% extends "main.html" %}
{% load staticfiles %}
{% block articles %}
<div class="row">
    <div class="col-11 col-md-6 offset-1">
        <h2>
            Дымные вести
        </h2>
        {% for article in articles %}
        <div class="bg-white shadow p-3 mb-1 bg-white rounded">  
            <h5>
                <a href="/article/get/{{ article.id }}" title="{{article.article_title}}">{{article.article_title}}</a>
                <small class="text-secondary text-right">{{article.article_date}}</small>
            </h5>
            <p class="text-justify">{{article.article_text}}</p>
            <a href="/article/addlike/{{ article.id }}" title="добавить лайт"> <img src="{% static "thumbs-up-icon.png"%}" width = "20px"/></a>{{article.article_likes}}
        </div>    
        {% endfor %}
                
    </div>
    <div class="col d-none d-md-block">
        <div id="sticky-anchor"></div>
            <div class="sticky right">
            <a href="/article/add" class="btn btn-primary shadow">+ Добавить статью</a>   
        </div>            
    </div>
    <div class="col col-md-6">
        <nav>
            <ul class="pagination justify-content-center m-3">
                {% if articles.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="/page/{{ articles.previous_page_number }}">Previous</a>        
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link" > Previous</span>        
                    </li>
                {% endif %}
                {% for page in pages %}
                    {% if page == articles.number %}
                        <li class="page-item active">
                            <span class="page-link">
                                {{page}}
                                <span class="sr-only">(current)</span>
                            </span>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="/page/{{ page }}">{{ page }}</a></li>
                    {% endif %}    
                {% endfor %}
                {% if articles.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="/page/{{ articles.next_page_number }}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link" >Next</span>        
                    </li>
                {% endif %}    
            </ul>
        </nav>
    </div>  
</div>
<a href="/article/add" class=" d-block d-md-none addbutton btn rounded-circle btn-lg btn-primary ">+</a>

  
{% endblock articles %}    
{% block script %}
    <script src="{% static "js/sticky-button.js"%}"></script>
{% endblock script %}